# Generated by Django 4.0.4 on 2022-05-26 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_p_delete_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='P',
            new_name='Post',
        ),
    ]
