# Generated by Django 4.0.4 on 2022-05-26 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_rename_p_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='image',
        ),
        migrations.RemoveField(
            model_name='task',
            name='number',
        ),
        migrations.AddField(
            model_name='task',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='interview.post'),
            preserve_default=False,
        ),
    ]
