# Generated by Django 4.0.4 on 2022-05-26 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_remove_task_image_remove_task_number_task_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspector', models.CharField(max_length=50, verbose_name='Проверяющий')),
                ('comment', models.TextField(verbose_name='Комментарий проверяющего')),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=50, verbose_name='Отчество')),
                ('date_of_passage', models.DateTimeField(verbose_name='Дата прохождения интервью')),
                ('comments', models.ManyToManyField(related_name='Комментарии', to='interview.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='interview.post')),
            ],
            options={
                'verbose_name': 'участник',
                'verbose_name_plural': 'участники',
            },
        ),
    ]
