# Generated by Django 4.0.4 on 2022-05-26 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0006_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='post',
            new_name='Должность',
        ),
        migrations.RemoveField(
            model_name='user',
            name='post',
        ),
        migrations.AddField(
            model_name='user',
            name='Должность',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='interview.post'),
            preserve_default=False,
        ),
    ]
