# Generated by Django 4.0.4 on 2022-05-26 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0008_rename_должность_task_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='post',
        ),
        migrations.RemoveField(
            model_name='user',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='user',
            name='post',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
