# Generated by Django 4.0.4 on 2022-05-26 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0018_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='examinee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='interview.user'),
            preserve_default=False,
        ),
    ]
