# Generated by Django 4.0.4 on 2022-05-26 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0019_remove_user_comments_comment_examinee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='post',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
