# Generated by Django 4.0.4 on 2022-06-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_user_unique_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_passage',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата прохождения интервью'),
        ),
    ]
