# Generated by Django 4.0.4 on 2022-06-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_user_date_of_passage_posix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_passage',
            field=models.DateTimeField(blank=True, verbose_name='Дата прохождения интервью'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_passage_posix',
            field=models.CharField(blank=True, max_length=50, verbose_name='Дата прохождения интервью posix'),
        ),
    ]
