# Generated by Django 4.0.4 on 2022-06-03 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_user_date_of_passage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_passage',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_of_passage_posix',
        ),
    ]
