# Generated by Django 4.0.4 on 2022-06-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_user_date_of_passage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_passage',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата прохождения интервью'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_passage_posix',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Дата прохождения интервью posix'),
        ),
    ]
