# Generated by Django 4.0.4 on 2022-06-03 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_user_date_of_passage_user_date_of_passage_posix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_passage_posix',
        ),
    ]
