# Generated by Django 4.0.4 on 2022-06-03 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_user_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='video',
        ),
    ]
