# Generated by Django 4.0.4 on 2022-06-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_user_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_passage',
        ),
        migrations.RemoveField(
            model_name='user',
            name='patronymic',
        ),
        migrations.RemoveField(
            model_name='user',
            name='unique_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='video',
        ),
        migrations.AddField(
            model_name='user',
            name='recommend',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Рекомендую'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(verbose_name='Вопрос'),
        ),
    ]
