# Generated by Django 4.0.4 on 2022-06-06 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_user_date_of_passage_remove_user_patronymic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='title',
            new_name='question',
        ),
    ]
