# Generated by Django 4.0.4 on 2022-06-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rename_title_question_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата прохождения интервью'),
        ),
    ]
