# Generated by Django 4.0.4 on 2022-06-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_user_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='video_link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Видео'),
        ),
    ]
