# Generated by Django 4.0.4 on 2022-06-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_user_video_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='video_link',
        ),
        migrations.AddField(
            model_name='user',
            name='media_link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Видео'),
        ),
        migrations.AddField(
            model_name='user',
            name='screen_link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Видео'),
        ),
    ]
