# Generated by Django 3.2.9 on 2022-06-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_user_video_link_user_media_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='media_link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Запись камера'),
        ),
        migrations.AlterField(
            model_name='user',
            name='screen_link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Запись экрана'),
        ),
    ]
