# Generated by Django 3.2.9 on 2022-06-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20220607_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='media_link',
        ),
        migrations.AlterField(
            model_name='user',
            name='screen_link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Видео'),
        ),
    ]
